name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v3

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies And Build
      run: |
        export GOPATH=`pwd`
        mkdir bin
        mkdir pkgs
        cd gcrmirrors
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            ../../bin/dep ensure
        fi
        go build -v .
